spring:
  application:
    name: todos-kotlin
  security:
    user:
      name: '{cipher}371487dc844b21a2bb032909ce19da2a238ee4c2ca02d537cf7ba12ba5113282'
      password: eaglepowers
todos:
  api:
    limit: 1024
management:
  endpoints:
    web:
      exposure:
        include: '*'

